# Form implementation generated from reading ui file 'LoginWindowV1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(950, 600)
        LoginWindow.setMinimumSize(QtCore.QSize(950, 600))
        LoginWindow.setMaximumSize(QtCore.QSize(950, 600))
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.windowStackWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.windowStackWidget.setGeometry(QtCore.QRect(0, 0, 950, 600))
        self.windowStackWidget.setStyleSheet("")
        self.windowStackWidget.setObjectName("windowStackWidget")
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setObjectName("pageLogin")
        self._background = QtWidgets.QLabel(parent=self.pageLogin)
        self._background.setGeometry(QtCore.QRect(0, 0, 951, 601))
        self._background.setStyleSheet("background-color: rgb(246, 239, 235);")
        self._background.setText("")
        self._background.setObjectName("_background")
        self._title = QtWidgets.QLabel(parent=self.pageLogin)
        self._title.setGeometry(QtCore.QRect(290, 230, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self._title.setFont(font)
        self._title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self._title.setObjectName("_title")
        self._loginButton = QtWidgets.QPushButton(parent=self.pageLogin)
        self._loginButton.setGeometry(QtCore.QRect(420, 310, 111, 31))
        self._loginButton.setObjectName("_loginButton")
        self.windowStackWidget.addWidget(self.pageLogin)
        self.pageDashboard = QtWidgets.QWidget()
        self.pageDashboard.setObjectName("pageDashboard")
        self._musicPLayerBackground = QtWidgets.QLabel(parent=self.pageDashboard)
        self._musicPLayerBackground.setGeometry(QtCore.QRect(0, 550, 950, 57))
        self._musicPLayerBackground.setStyleSheet("background-color: rgb(38, 38, 38);")
        self._musicPLayerBackground.setText("")
        self._musicPLayerBackground.setObjectName("_musicPLayerBackground")
        self._menuBackground = QtWidgets.QLabel(parent=self.pageDashboard)
        self._menuBackground.setGeometry(QtCore.QRect(0, 0, 198, 551))
        self._menuBackground.setStyleSheet("background-color: rgb(64, 64, 64);")
        self._menuBackground.setText("")
        self._menuBackground.setObjectName("_menuBackground")
        self.feedStackedWidget = QtWidgets.QStackedWidget(parent=self.pageDashboard)
        self.feedStackedWidget.setGeometry(QtCore.QRect(200, 0, 751, 551))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.feedStackedWidget.setFont(font)
        self.feedStackedWidget.setStyleSheet("background-color: rgb(246, 239, 235);")
        self.feedStackedWidget.setObjectName("feedStackedWidget")
        self._homePage = QtWidgets.QWidget()
        self._homePage.setObjectName("_homePage")
        self._comingSoonLabel = QtWidgets.QLabel(parent=self._homePage)
        self._comingSoonLabel.setGeometry(QtCore.QRect(0, -20, 291, 231))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(64)
        self._comingSoonLabel.setFont(font)
        self._comingSoonLabel.setWordWrap(False)
        self._comingSoonLabel.setObjectName("_comingSoonLabel")
        self.feedStackedWidget.addWidget(self._homePage)
        self._playlistPage = QtWidgets.QWidget()
        self._playlistPage.setObjectName("_playlistPage")
        self._playlistLabel = QtWidgets.QLabel(parent=self._playlistPage)
        self._playlistLabel.setGeometry(QtCore.QRect(0, -10, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(64)
        self._playlistLabel.setFont(font)
        self._playlistLabel.setObjectName("_playlistLabel")
        self.scrollArea = QtWidgets.QScrollArea(parent=self._playlistPage)
        self.scrollArea.setGeometry(QtCore.QRect(0, 110, 751, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self._loadedPlaylistScrollArea = QtWidgets.QWidget()
        self._loadedPlaylistScrollArea.setGeometry(QtCore.QRect(0, 0, 749, 439))
        self._loadedPlaylistScrollArea.setObjectName("_loadedPlaylistScrollArea")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self._loadedPlaylistScrollArea)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self._loadedPlaylistScrollArea)
        self.feedStackedWidget.addWidget(self._playlistPage)
        self.widget = QtWidgets.QWidget(parent=self.pageDashboard)
        self.widget.setGeometry(QtCore.QRect(0, 0, 102, 78))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self._homeButton = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._homeButton.setFont(font)
        self._homeButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self._homeButton.setStyleSheet("text-align: left;\n"
"border: none;\n"
"background-color: transparent;\n"
"background: none;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/homeicon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self._homeButton.setIcon(icon)
        self._homeButton.setIconSize(QtCore.QSize(26, 26))
        self._homeButton.setObjectName("_homeButton")
        self.verticalLayout.addWidget(self._homeButton)
        self._playlistButton = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._playlistButton.setFont(font)
        self._playlistButton.setStyleSheet("text-align: left;\n"
"border: none;\n"
"background-color: transparent;\n"
"background: none;\n"
"padding: 0;\n"
"margin: 0;\n"
"color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/playlisticon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self._playlistButton.setIcon(icon1)
        self._playlistButton.setIconSize(QtCore.QSize(26, 26))
        self._playlistButton.setObjectName("_playlistButton")
        self.verticalLayout.addWidget(self._playlistButton)
        self.windowStackWidget.addWidget(self.pageDashboard)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.windowStackWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self._title.setText(_translate("LoginWindow", "Untitled PlaylistApp"))
        self._loginButton.setText(_translate("LoginWindow", "Login to Spotify"))
        self._comingSoonLabel.setText(_translate("LoginWindow", "Coming\n"
"soon..."))
        self._playlistLabel.setText(_translate("LoginWindow", "Playlists"))
        self._homeButton.setText(_translate("LoginWindow", "Home"))
        self._playlistButton.setText(_translate("LoginWindow", "Playlists"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
