# Form implementation generated from reading ui file 'PlaylistCardV1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class PlaylistCard(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(128, 169)
        Form.setMinimumSize(QtCore.QSize(128, 169))
        self._playlistBackColor = QtWidgets.QLabel(parent=Form)
        self._playlistBackColor.setGeometry(QtCore.QRect(0, 0, 128, 169))
        self._playlistBackColor.setStyleSheet("\n"
"border-radius: 8px;\n"
"background-color: rgb(217, 217, 217);")
        self._playlistBackColor.setText("")
        self._playlistBackColor.setObjectName("_playlistBackColor")
        self._playlistImage = QtWidgets.QLabel(parent=Form)
        self._playlistImage.setGeometry(QtCore.QRect(14, 11, 100, 105))
        self._playlistImage.setStyleSheet("background-color: rgb(255, 25, 163);")
        self._playlistImage.setText("")
        self._playlistImage.setObjectName("_playlistImage")
        self._playlistName = QtWidgets.QLabel(parent=Form)
        self._playlistName.setGeometry(QtCore.QRect(10, 120, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self._playlistName.setFont(font)
        self._playlistName.setObjectName("_playlistName")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self._playlistName.setText(_translate("Form", "PlaylistName"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = PlaylistCard()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
