# Form implementation generated from reading ui file 'playlistAlbumTest.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self._title = QtWidgets.QLabel(parent=self.centralwidget)
        self._title.setGeometry(QtCore.QRect(160, 110, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self._title.setFont(font)
        self._title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self._title.setObjectName("_title")
        self._background = QtWidgets.QLabel(parent=self.centralwidget)
        self._background.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self._background.setStyleSheet("background-color: rgb(197, 180, 255);")
        self._background.setText("")
        self._background.setObjectName("_background")
        self._albumField = QtWidgets.QLineEdit(parent=self.centralwidget)
        self._albumField.setGeometry(QtCore.QRect(180, 230, 311, 21))
        self._albumField.setObjectName("_albumField")
        self._submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self._submitButton.setGeometry(QtCore.QRect(500, 230, 75, 24))
        self._submitButton.setObjectName("_submitButton")
        self._image = QtWidgets.QLabel(parent=self.centralwidget)
        self._image.setGeometry(QtCore.QRect(250, 300, 250, 250))
        self._image.setText("")
        self._image.setPixmap(QtGui.QPixmap("../../../../Downloads/tyler.jpg"))
        self._image.setScaledContents(True)
        self._image.setObjectName("_image")
        self._title2 = QtWidgets.QLabel(parent=self.centralwidget)
        self._title2.setGeometry(QtCore.QRect(330, 190, 81, 16))
        self._title2.setObjectName("_title2")
        self._background.raise_()
        self._title.raise_()
        self._albumField.raise_()
        self._submitButton.raise_()
        self._image.raise_()
        self._title2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self._title.setText(_translate("MainWindow", "Add a album cover"))
        self._albumField.setPlaceholderText(_translate("MainWindow", "Album name..."))
        self._submitButton.setText(_translate("MainWindow", "Submit"))
        self._title2.setText(_translate("MainWindow", "Spotify API test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
